# Generated by Django 3.2.4 on 2022-05-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220527_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcontributor',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='sample',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='sample',
            field=models.FileField(blank=True, null=True, upload_to='book_samples/'),
        ),
    ]
